# Generated by Django 2.0.7 on 2018-07-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'start'), ('end', 'end')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call_id', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
            ],
        ),
    ]
